### ISSUE TITLE
Checklist for a well-behaved daemon (PEP 3143)

### ISSUE THREAD

**Issue by tomschr** [openSUSE/docserv#59]
## Problem

I studied recently some papers about daemons in Python. Not sure, if this is relevant for this script, but I think, it's worth to dig a bit deeper. Especially as the daemon run as root user.

## Expected behaviour

According to [StackOverflow](https://stackoverflow.com/a/688448), we could check the script:

* [ ] prevent core dumps (many daemons run as root, and core dumps can contain sensitive information)
* [ ] behave correctly inside a chroot goal
* [ ] set UID, GID, working directory, umask, and other process parameters appropriately for the use case
* [ ] relinquish elevated suid, sgid privileges
* [ ] close all open file descriptors, with exclusions depending on the use case
* [ ] behave correctly if started inside an already-detached context, such as init, inetd, etc.
* [ ] set up signal handlers for sensible daemon behaviour, but also with specific handlers determined by the use case
* [ ] redirect the standard streams stdin, stdout, stderr since a daemon process no longer has a controlling terminal
* [ ] handle a PID file as a cooperative advisory lock, which is a whole can of worms in itself with many contradictory but valid ways to behave
* [ ] allow proper cleanup when the process is terminated
* [ ] actually become a daemon process without leading to zombies

> All of these are covered by the [PEP 3143](http://www.python.org/dev/peps/pep-3143) “Standard daemon process library” specification. The [python-daemon](http://pypi.python.org/pypi/python-daemon/) reference implementation works on Python 2.7 or later, and Python 3.2 or later.

**Comment by sknorr** [comment]
@tomschr What kind of issue is that? Why not just go through the check list yourself and report your findings?

**Comment by tomschr** [comment]
@sknorr Well, we discussed that before and Sven already saw it. I don't know the source code well enough to make any judgements ATM. So it's basically a kind of reminder as the script is not a "real" daemon.
